---
x-airflow-common:
  &airflow-common
  build:
    context: .
    # кастомный докерфал для Airflow (либы из requirements.txt (duckdb) и расширения для duckdb уже установлены)
    dockerfile: Dockerfile.airflow
  image: airflow_custom:latest
  environment:
    &airflow-common-env
    TZ: Europe/Moscow
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow/airflow
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
  networks:
    - data_network
  # /var/run/docker.sock чтобы Airflow мог сам запускать контейнеры (юзается для DockerOperator)
  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
    - /var/run/docker.sock:/var/run/docker.sock
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    postgres_airflow:
      condition: service_healthy
    minio:
      condition: service_healthy
    postgres_dwh:
      condition: service_healthy
  deploy:
    resources:
      limits:
        memory: 2G # ограничение памяти для Airflow

services:
  minio:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    container_name: minio
    networks:
      - data_network
    volumes:
      - ./minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      TZ: Europe/Moscow
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
# ждет когда minio поднимется, создает бакеты raw и silver
  minio-init:
    image: minio/mc:RELEASE.2025-02-21T16-00-46Z
    networks:
      - data_network
    container_name: minio_init
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}; do 
        echo 'Waiting for MinIO...'; 
        sleep 2; 
      done;
      
      /usr/bin/mc mb myminio/raw --ignore-existing;
      /usr/bin/mc mb myminio/silver --ignore-existing;
      
      echo 'Buckets created successfully!';
      exit 0;
      "
  postgres_dwh:
    image: postgres:13
    networks:
      - data_network
    container_name: postgres_dwh
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_dwh_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d/ # DDL для создания схем и таблиц в DWH, ток при первом запуске
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
  postgres_airflow:
    image: postgres:13
    networks:
      - data_network
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      TZ: Europe/Moscow
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
  metabase:
    image: metabase/metabase:v0.58.4
    container_name: metabase
    networks:
      - data_network
    volumes:
      - ./metabase_data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db # SQLite для Metabase
    ports:
      - "3000:3000"
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
  backend:
    build: ./backend
    image: fastapi_backend:latest
    container_name: fastapi
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres_dwh:
        condition: service_healthy
    networks:
      - data_network
    restart: always
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "${_AIRFLOW_WWW_PORT}:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

# выполняет миграцию базы, создает админского юзера, создает коннекшены для postgres и minio, подтягивает парометры из .env
  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate && \
        airflow users create \
          --username "${_AIRFLOW_WWW_USER_USERNAME}" \
          --password "${_AIRFLOW_WWW_USER_PASSWORD}" \
          --firstname Ilyas \
          --lastname Admin \
          --role Admin \
          --email "${_AIRFLOW_WWW_USER_EMAIL}" || true && \
        airflow connections add 'pg_conn' \
          --conn-type 'postgres' \
          --conn-login "${POSTGRES_USER}" \
          --conn-password "${POSTGRES_PASSWORD}" \
          --conn-host 'postgres_dwh' \
          --conn-port '5432' \
          --conn-schema "${POSTGRES_DB}" || true && \
        airflow connections add 's3_conn' \
          --conn-type 'aws' \
          --conn-login "${MINIO_ROOT_USER}" \
          --conn-password "${MINIO_ROOT_PASSWORD}" \
          --conn-extra "{\"endpoint_url\": \"http://minio:9000\", \"addressing_style\": \"path\", \"region_name\": \"ru-central1\"}" || true
    environment:
      <<: *airflow-common-env
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD}
      _AIRFLOW_WWW_USER_EMAIL: ${_AIRFLOW_WWW_USER_EMAIL}
    user: "0:0"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}:/sources

networks:
  data_network:
    driver: bridge
    name: data_network

volumes:
  postgres_airflow_data:
    name: postgres_airflow_data
  postgres_dwh_data:
    name: postgres_dwh_data
